title: "rubberduck.log"
description: "Sysadmin, geek, papa. Tutos IT, retours d'expérience, culture."
author: "RubberDucking35"
url: "https://rubberducking35.github.io"
baseurl: ""

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
